# Generated by Django 3.0.3 on 2021-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210928_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/img/flags.png', upload_to='media/'),
        ),
    ]
